export const FETCH_USER = "FETCH_USER";
export const FETCH_SURVEYS = "FETCH_SURVEYS";
export const SHOW_LOGIN_POPUP = "SHOW_LOGIN_POPUP";
export const SHOW_CREDITS_POPUP = "SHOW_CREDITS_POPUP";
export const CLOSE_LOGIN_POPUP = "CLOSE_LOGIN_POPUP";
export const CLOSE_CREDITS_POPUP = "CLOSE_CREDITS_POPUP";
